name: Build

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B Release -DCMAKE_BUILD_TYPE=Release -A x64 .
          cmake --build Release --config Release
          cp README.md Release/
          cp LICENSE.txt Release/
          cp Release/Release/menu.exe Release/
      - name: Publish artifacts
        uses: actions/upload-artifact@v7
        with:
          name: menu-windows
          path: |
            Release/README.md
            Release/LICENSE.txt
            Release/menu.exe
            Release/resources/

  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends git ca-certificates g++ make cmake zlib1g-dev libasound-dev libxkbcommon-dev libdrm-dev libgl1-mesa-dev libgbm-dev libwayland-dev libdecor-0-dev
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -B Release -DCMAKE_BUILD_TYPE=Release -DSDL_X11=OFF .
          cmake --build Release
          cp README.md Release/
          cp LICENSE.txt Release/
      - name: Publish artifacts
        uses: actions/upload-artifact@v7
        with:
          name: menu-linux
          path: |
            Release/README.md
            Release/LICENSE.txt
            Release/menu.exe
            Release/resources/
